### ISSUE TITLE
I'm going mad with ACL ! please help

### ISSUE THREAD

**Issue by scenaristeur** [Otto-AA/solid-acl-utils#4]
Hi @Otto-AA  , i want to create two folder & set the authorization via solid-acl-utils.
I use solid-file-client to create folder like that 

```
import * as SolidAclUtils from 'solid-acl-utils/dist/browser/solid-acl-utils.bundle.js'
console.log(SolidAclUtils)
import * as SolidFileClient from 'solid-file-client/dist/window/solid-file-client.bundle.js'

// You could also use SolidAclUtils.Permissions.READ instead of following
// This is just more convenient
const { AclApi, AclDoc, AclParser, AclRule, Permissions, Agents } = SolidAclUtils
const { READ, WRITE, APPEND, CONTROL } = Permissions

class ShighlActivity {
  //  https://www.w3.org/TR/activitystreams-vocabulary/
  constructor () {
    console.log("Shighl Activity loaded")
    this.fc   = new SolidFileClient(auth)
    //  this.testacl()
  }

  async testacl(webId, root){
  //  console.log(webid)
    let module = this

    let inbox = root+'inbox/'
    let outbox = root+'outbox/'
// create folders
    if( !(await module.fc.itemExists(inbox)) ) {
      await module.fc.createFolder(inbox) // only create if it doesn't already exist
    }

    if( !(await module.fc.itemExists(outbox)) ) {
      await module.fc.createFolder(outbox) // only create if it doesn't already exist
    }

      // Passing it the fetch from solid-auth-client
   const fetch = auth.fetch.bind(auth)

    const aclApi = new AclApi(fetch, { autoSave: true })
  const acl_outbox = await aclApi.loadFromFileUrl(outbox)
    const acl_inbox = await aclApi.loadFromFileUrl(inbox)

    // Note: Workaround, because currently no default permissions are copied when a new acl file is created. Not doing this could result in having no CONTROL permissions after the first acl.addRule call
    if (!acl_outbox.hasRule(Permissions.ALL, webId)) {
    await acl_outbox.addRule(Permissions.ALL, webId)
  }

    if (!acl_inbox.hasRule(Permissions.ALL, webId)) {
    await acl_inbox.addRule(Permissions.ALL, webId)
  }

  await acl_outbox.addRule(APPEND, Agents.AUTHENTICATED)
  const agentsOutbox = acl_outbox.getAgentsWith(APPEND)
  console.log([...agentsOutbox.webIds]) // array containing all webIds which have write access
  console.log([...agentsOutbox.groups])
  console.log(agentsOutbox.hasPublic())
  console.log(agentsOutbox.hasAuthenticated()) // Authenticated means everyone who is logged in

  await acl_inbox.addRule(APPEND, Agents.AUTHENTICATED)
  const agentsInbox = acl_inbox.getAgentsWith(APPEND)
  console.log([...agentsInbox.webIds]) // array containing all webIds which have write access
  console.log([...agentsInbox.groups])
  console.log(agentsInbox.hasPublic())
  console.log(agentsInbox.hasAuthenticated()) // Authenticated means everyone who is logged in

}
```
that i call with something like ```activity.testacl(pod.webId, storage+"public/test_acl7/")```

But i'm going mad  : It seems that I loose the authorization for the second folder. 

when I use 
```
  const acl_inbox = await aclApi.loadFromFileUrl(inbox)
    const acl_outbox = await aclApi.loadFromFileUrl(outbox) 
```
acl_outbox is in second position, I lost access to the outbox folder

![image](https://user-images.githubusercontent.com/4020744/78472024-f8d67e00-7735-11ea-8794-edb2050fae1d.png)

When I use 
```
    const acl_outbox = await aclApi.loadFromFileUrl(outbox)
    const acl_inbox = await aclApi.loadFromFileUrl(inbox)
```
acl_inbox is in second position , and I lost acces to inbox folder

![image](https://user-images.githubusercontent.com/4020744/78472064-54087080-7736-11ea-8210-ce018f0223a8.png)

I'm doing something wrong or becoming crazy ? is it a cache api issue or something like that ? 
Do I have to separate the two acl operations ? 

Thxs

**Comment by scenaristeur** [comment]
Creating 2 aclApi seems to worrk as Expected : 
```
    const aclApi_outbox = new AclApi(fetch, { autoSave: true })
    const aclApi_inbox = new AclApi(fetch, { autoSave: true })

    const acl_outbox = await aclApi_outbox.loadFromFileUrl(outbox)
    const acl_inbox = await aclApi_inbox.loadFromFileUrl(inbox)
```
![image](https://user-images.githubusercontent.com/4020744/78472305-e8270780-7737-11ea-9eb4-ea4f2e470e44.png)

**Comment by Otto-AA** [comment]
You should use one instance of `AclApi` per acl file, like in your last example. (Looking back at it this is rather counter-intuitive, but yeah... that's how it is currently)

Is there another problem you've encountered?

And some side notes:
- This project is in WIP status, so I wouldn't suggest to use it for important data. Also I don't know if I have the time to maintain it, so if the solid spec changes, this project probably won't get updated
- I've already patched it to load the default acl from the parent (which means that `Workaround, because...` is not necessary anymore). Apparently forgot to patch the documentation for it
- if you use fc.createFolder with `merge: KEEP_SOURCE` it won't overwrite existing folders (it's the same

**Comment by scenaristeur** [comment]
Thxs, ok, i will use one AclApi per acl file, but I got another question. 
I want to set the rules for an inbox folder that is in the /public folder

- Authenticated Agent as Submiter
- Owner WebId as Owner
- and remove Public as Viewer

So I used 
```
  if (!acl_inbox.hasRule(Permissions.ALL, webId)) {
    await acl_inbox.addRule(Permissions.ALL, webId)
  }

  await acl_inbox.addRule(APPEND, Agents.AUTHENTICATED)
  await acl_inbox.deleteRule(READ, Agents.PUBLIC)
```

But it gives me an "unusual combination"

![image](https://user-images.githubusercontent.com/4020744/78793237-668ede00-79b2-11ea-8a05-f45e95dbd2ad.png)


![image](https://user-images.githubusercontent.com/4020744/78793134-452df200-79b2-11ea-9793-14aed51158e8.png)

```
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#owner> a acl:Authorization;
    acl:agent <https://spoggy-test.solid.community/profile/card#me>;
    acl:accessTo <https://spoggy-test.solid.community/public/shighl_test/inbox/>;
    acl:mode acl:Read, acl:Write, acl:Control.
<https://spoggy-test.solid.community/public/shighl_test/inbox/#solid-acl-parser-rule-0> a acl:Authorization;
    acl:agent <https://spoggy-test.solid.community/profile/card#me>;
    acl:accessTo <https://spoggy-test.solid.community/public/shighl_test/inbox/>;
    acl:mode acl:Read, acl:Write, acl:Append, acl:Control.
<https://spoggy-test.solid.community/public/shighl_test/inbox/#solid-acl-parser-rule-1> a acl:Authorization;
    acl:agentClass acl:AuthenticatedAgent;
    acl:accessTo <https://spoggy-test.solid.community/public/shighl_test/inbox/>;
    acl:mode acl:Append.

```

As you can see , there are two entries for "https://spoggy-test.solid.community/profile/card#me" one without acl:Append and the other with acl:Append.
I think the first one is herited from the parent, by default and the second one is created by 
the
```
await acl_inbox.addRule(Permissions.ALL, webId)
``` 
you told "don't forget", but in this case it creates a conflict, so I think that for Permissions.ALL, Append is not necessary, confirmed by @bourgeois here https://gitlab.com/solid.community/support/-/issues/13#note_318161434.

Another problem is that it creates absolutes uri instead of relatives ... What can I do to get relative URIs ?

**Comment by scenaristeur** [comment]
But don't worry for this issue, as I need more complex rules like 
```
@prefix : <#>.
@prefix n0: <http://www.w3.org/ns/auth/acl#>.
@prefix inbox: <./>.
@prefix c: </profile/card#>.

:Append
    a n0:Authorization;
    n0:accessTo inbox:;
    n0:agentClass n0:AuthenticatedAgent;
    n0:mode n0:Append.
:AppendDefault
    a n0:Authorization;
    n0:agentClass n0:AuthenticatedAgent;
    n0:default inbox:;
    n0:mode n0:Append;
    n0:origin <http://localhost:9000>.
:ControlReadWrite
    a n0:Authorization;
    n0:accessTo inbox:;
    n0:agent c:me;
    n0:mode n0:Control, n0:Read, n0:Write.
```
i will try creating .acl file another way ;-)

**Comment by Otto-AA** [comment]
```javascript
  if (!acl_inbox.hasRule(Permissions.ALL, webId)) {
    await acl_inbox.addRule(Permissions.ALL, webId)
  }

  await acl_inbox.addRule(APPEND, Agents.AUTHENTICATED)
  await acl_inbox.deleteRule(READ, Agents.PUBLIC)
```

As mentioned before, you don't need to check for the first owner as it automatically inherits from the parent. You could also change the if statement to `if (!acl_inbox.hasRule([CONTROL, READ, WRITE], webId)) {`, I guess that it wouldn't duplicate it for the owner this way. But that shouldn't be necessary too.

And yes, @bourgeois is right that if the user has WRITE he automatically can APPEND too. I think for your use case (and most others) it doesn't matter. But (afaik) it's still semantically different if the user has WRITE and APPEND or only APPEND. For instance when the WRITE permissions are revoked, in the first case the user would still be able to APPEND, in the second he wouldn't.  That's why Permissions.ALL has all four permissions.

> Another problem is that it creates absolutes uri instead of relatives ... What can I do to get relative URIs ?

I've updated the dependencies, it now uses more relative urls.

**Comment by Otto-AA** [comment]
> 

> But don't worry for this issue, as I need more complex rules like

I think this would be enough for your rules (not tested):
```javascript
acl_inbox.addDefaultRule(APPEND, Agents.AUTHENTICATED)
```

The urls won't be shortened that much, but for the permissions it should work.

This would be the one for the not-default permissions, but I think it is unnecessary here as they are the same as the default permissions:
```javascript
acl_inbox.addRule(APPEND, Agents.AUTHENTICATED)
```

And for the owner, but these should be inherited anyway:
```javascript
acl_inbox.addRule([READ, WRITE, CONTROL], ownerWebId)
```

**Comment by scenaristeur** [comment]
thxs
